.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH vhs-86 1  "vhs-86 0.7.0" 
.SH NAME
vhs\-86 \- A retro terminal file manager with synthwave aesthetics
.SH SYNOPSIS
\fBvhs\-86\fR [\fB\-H\fR|\fB\-\-hidden\fR] [\fB\-t\fR|\fB\-\-theme\fR] [\fB\-c\fR|\fB\-\-config\fR] [\fB\-\-no\-preview\fR] [\fB\-\-no\-highlight\fR] [\fB\-\-cd\-on\-quit\fR] [\fB\-\-no\-mouse\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIPATH\fR] 
.SH DESCRIPTION
A retro terminal file manager with synthwave aesthetics
.SH OPTIONS
.TP
\fB\-H\fR, \fB\-\-hidden\fR
Show hidden files by default
.TP
\fB\-t\fR, \fB\-\-theme\fR \fI<THEME>\fR
Use a specific color theme
.TP
\fB\-c\fR, \fB\-\-config\fR \fI<FILE>\fR
Use a custom config file
.TP
\fB\-\-no\-preview\fR
Disable file preview panel
.TP
\fB\-\-no\-highlight\fR
Disable syntax highlighting in previews
.TP
\fB\-\-cd\-on\-quit\fR
Print current directory on quit (for shell integration)
.TP
\fB\-\-no\-mouse\fR
Disable mouse support
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIPATH\fR] [default: .]
Starting directory path (defaults to current directory)
.SH VERSION
v0.7.0
.SH AUTHORS
synthalorian

